### ISSUE TITLE
Train dataset?

### ISSUE THREAD

**Issue by harrett** [aashrafh/Mozart#17]
Thank you very much for this wonderful repo.
I am doing research works on OMR, and tried the command:
`python3 main.py <input directory path> <output directory path>`
it works fine. But when I executed this:
`python3 train.py`
got error with:
`ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.`
So I found the dataset directory missed in the project:
`dataset_path = 'train_data/data'`
Can you commit it again?

Thanks!

**Comment by aashrafh** [comment]
The dataset is uploaded to [Google Drive](https://drive.google.com/drive/folders/1OVGA3CGnEKjyg_k_L8MP2RO5R3oDIbHE?usp=sharing) because its size is large. So, please, download it and place it in the mentioned directory.
