### ISSUE TITLE
generate audio file

### ISSUE THREAD

**Issue by harryhan618** [aashrafh/Mozart#6]
Hello, good to see this repo! May I ask do you have a plan to incorperate a tool to generate audio file from text representation?

**Comment by aashrafh** [comment]
Currently, there is no plan for that but we are open to any suggestions or contributions.

**Comment by Matthew1172** [comment]
I am working on a python script to convert the output of this program into [ABC notation](https://en.wikipedia.org/wiki/ABC_notation) which can be used to create midi files using the program [abc2midi](https://abcmidi.sourceforge.io/)
