### ISSUE TITLE
Error for creating conda env

### ISSUE THREAD

**Issue by jiaboli007** [aashrafh/Mozart#8]
I got the following error:

conda env create -f requirements.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

I tried on two different MacBook Pro, and got the same errors. 

It will be great to provide some hints how to solve this problem. 

Thanks!

**Comment by aashrafh** [comment]
Sorry, but I couldn't re-generate the error! Everything works just fine.

![Screenshot_20210317_153608](https://user-images.githubusercontent.com/40968967/111476258-a91a7800-8736-11eb-9eaf-e515122f60be.png)

**Comment by jiaboli007** [comment]
Maybe it is a platform dependent issue. Which platform are you developing Mozart? Linux? I am testing on macOS Catalina 10.15.7

**Comment by aashrafh** [comment]
I'm using Linux 5.10.15-1-MANJARO and tested it on other Linux platforms and Windows works fine but didn't test it on macOS.

**Comment by jiaboli007** [comment]
Thank you so much for your information. I will try on a Linux machine. I believe Mozart is a great open source project, I really appreciate your team have put things together and a lot of people will benefit from this work.  It will be nice to get Mozart working on macOS, as a lot of high-end developers for music are using Mac.

**Comment by ken830** [comment]
Same issue for me on Windows 64-bit:

`(base) C:\Users\Ken\Downloads\Mozart>conda env create -f requirements.yml
Collecting package metadata (repodata.json): done
Solving environment: failed`

**Comment by AndyTQ** [comment]
I am having the same issue as @ken830 , on Windows 10:
`(mozart) C:\Users\35171\Desktop\Codebase\Mozart\Mozart-main>conda env create -f requirements.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - jupyter_server==1.1.3=py37h89c1867_0
  - libgcc-ng==9.3.0=h5dbcf3e_17
  - gst-plugins-base==1.14.5=h0935bb2_2
  - c-ares==1.17.1=h36c2ea0_0
  - kiwisolver==1.3.1=py37hc928c03_0
  - fontconfig==2.13.1=h736d332_1003
  - libgfortran5==9.3.0=he4bcb1c_17
  - libxcb==1.13=h14c3975_1002
  - libuuid==2.32.1=h7f98852_1000
  - xorg-libx11==1.6.12=h516909a_0
  - bzip2==1.0.8=h7f98852_4
  - libclang==11.0.0=default_ha5c780c_2
  - sqlite==3.34.0=h74cdb3f_0
  - py-opencv==4.5.0=py37h888b3d9_4
  - zlib==1.2.11=h516909a_1010
  - imutils==0.5.3=py37h89c1867_3
  - mysql-libs==8.0.22=h1fd7589_1
  - xorg-libxrender==0.9.10=h516909a_1002
  - gettext==0.19.8.1=h0b5b191_1005
  - pixman==0.40.0=h36c2ea0_0
  - python==3.7.9=hffdb5ce_0_cpython
  - yaml==0.2.5=h7b6447c_0
  - gstreamer==1.18.2=ha23517c_0
  - cairo==1.16.0=h7979940_1007
  - pywavelets==1.1.1=py37h7b6447c_2
  - pandoc==2.11.3.1=h7f98852_0
  - pthread-stubs==0.4=h36c2ea0_1001
  - libgfortran-ng==9.3.0=he4bcb1c_17
  - numpy==1.19.4=py37haa41c4c_2
  - lcms2==2.11=hcbb858e_1
  - libedit==3.1.20191231=he28a2e2_2
  - expat==2.2.9=he1b5a44_2
  - xorg-libxext==1.3.4=h516909a_0
  - glib==2.66.4=hcd2ae1e_1
  - setuptools==49.6.0=py37he5f6b98_2
  - _openmp_mutex==4.5=1_gnu
  - tifffile==2020.10.1=py37hdd07704_2
  - brotlipy==0.7.0=py37hb5d75c8_1001
  - scikit-image==0.17.2=py37hdf5156a_0
  - xz==5.2.5=h516909a_1
  - nbconvert==6.0.7=py37h89c1867_3
  - xorg-kbproto==1.0.7=h14c3975_1002
  - tornado==6.1=py37h4abf009_0
  - libxml2==2.9.10=h72842e0_3
  - readline==8.0=he28a2e2_2
  - mysql-common==8.0.22=ha770c72_1
  - pillow==8.0.1=py37h63a5d19_0
  - terminado==0.9.1=py37h89c1867_1
  - graphite2==1.3.13=h58526e2_1001
  - libev==4.33=h516909a_1
  - libstdcxx-ng==9.3.0=h2ae2ef3_17
  - nss==3.60=hb5efdd6_0
  - lame==3.100=h14c3975_1001
  - ncurses==6.2=h58526e2_4
  - libevent==2.1.10=hcdb4288_3
  - lz4-c==1.9.2=he1b5a44_3
  - krb5==1.17.2=h926e7f8_0
  - tk==8.6.10=h21135ba_1
  - libopenblas==0.3.12=pthreads_h4812303_1
  - dbus==1.13.6=hfdff14a_1
  - ld_impl_linux-64==2.35.1=hea4e1c9_1
  - xorg-libice==1.0.10=h516909a_0
  - x264==1!152.20180806=h14c3975_0
  - libllvm11==11.0.0=he513fc3_0
  - jupyter_core==4.7.0=py37h89c1867_0
  - anyio==2.0.2=py37h89c1867_2
  - gnutls==3.6.13=h85f3911_1
  - libsodium==1.0.18=h36c2ea0_1
  - libpng==1.6.37=h21135ba_2
  - chardet==4.0.0=py37h89c1867_0
  - libglib==2.66.4=h164308a_1
  - pyrsistent==0.17.3=py37h4abf009_1
  - mistune==0.8.4=py37h4abf009_1002
  - libiconv==1.16=h516909a_0
  - icu==68.1=h58526e2_0
  - importlib-metadata==3.3.0=py37h89c1867_2
  - libssh2==1.9.0=hab1572f_5
  - markupsafe==1.1.1=py37hb5d75c8_2
  - qt==5.12.9=h9d6b050_2
  - pcre==8.44=he1b5a44_0
  - certifi==2020.12.5=py37h89c1867_0
  - ca-certificates==2020.12.5=ha878542_0
  - libcurl==7.71.1=hcdd3856_8
  - jasper==1.900.1=h07fcdf6_1006
  - libtiff==4.2.0=hdc55705_0
  - harfbuzz==2.7.2=h5cf4720_2
  - xorg-libxdmcp==1.1.3=h516909a_0
  - nettle==3.6=he412f7d_0
  - xorg-libsm==1.2.3=h84519dc_1000
  - libffi==3.3=h58526e2_2
  - pysocks==1.7.1=py37he5f6b98_2
  - cryptography==3.3.1=py37h7f0c10b_0
  - jpeg==9d=h36c2ea0_0
  - argon2-cffi==20.1.0=py37h4abf009_2
  - xorg-xproto==7.0.31=h7f98852_1007
  - pyyaml==5.3.1=py37h7b6447c_1
  - libgomp==9.3.0=h5dbcf3e_17
  - scipy==1.5.3=py37h14a347d_0
  - xorg-renderproto==0.11.1=h14c3975_1002
  - libwebp-base==1.1.0=h36c2ea0_3
  - openssl==1.1.1i=h7f98852_0
  - ffmpeg==4.3.1=h3215721_1
  - xorg-xextproto==7.3.0=h14c3975_1002
  - freetype==2.10.4=h7ca028e_0
  - xorg-libxau==1.0.9=h14c3975_0
  - notebook==6.1.6=py37h89c1867_0
  - pyzmq==20.0.0=py37h5a562af_1
  - gmp==6.2.1=h58526e2_0
  - libpq==12.3=h255efa7_3
  - cytoolz==0.11.0=py37h7b6447c_0
  - openh264==2.1.1=h8b12597_0
  - scikit-learn==0.23.2=py37h0573a6f_0
  - matplotlib-base==3.3.3=py37h4f6019d_0
  - zeromq==4.3.3=h58526e2_3
  - libxkbcommon==1.0.3=he3ba5ed_0
  - hdf5==1.10.6=nompi_h6a2412b_1112
  - cffi==1.14.4=py37hc58025e_1
  - sniffio==1.2.0=py37h89c1867_0
  - zstd==1.4.5=h6597ccf_2
  - _libgcc_mutex==0.1=conda_forge
  - libnghttp2==1.41.0=h8cfc5f6_2
  - nspr==4.29=he1b5a44_1`

**Comment by aashrafh** [comment]
@AndyTQ @ken830
Please replace the content of the ```requirement.yml``` file with the following and try again:

```
name: mozart
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=2.0.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - cloudpickle=1.6.0
  - cryptography=3.3.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2020.12.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.18.2
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=3.3.0
  - importlib_metadata=3.3.0
  - imutils=0.5.3
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyter_server=1.1.3
  - jupyterlab=3.0.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.4
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.0.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libopencv=4.5.0
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.3
  - mistune=0.8.4
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nbclassic=0.2.5
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - nettle=3.6
  - networkx=2.5
  - notebook=6.1.6
  - nspr=4.29
  - nss=3.60
  - numpy=1.19.4
  - olefile=0.46
  - opencv=4.5.0
  - openh264=2.1.1
  - openssl=1.1.1i
  - packaging=20.8
  - pandoc=2.11.3.1
  - pandocfilters=1.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - pixman=0.40.0
  - prometheus_client=0.9.0
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py-opencv=4.5.0
  - pycparser=2.20
  - pygments=2.7.3
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.12.9
  - readline=8.0
  - requests=2.25.1
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.34.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - autopep8==1.5.4
    - pycodestyle==2.6.0
    - toml==0.10.2
```

**Comment by ken830** [comment]
@aashrafh: Thank you. I tried with new requirements.yml from above, and this is what I see. It's a much shorter list.

```
(base) C:\Users\Ken\Downloads\Mozart>conda env create -f requirements.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libgfortran5=9.3.0
  - libgcc-ng=9.3.0
  - ld_impl_linux-64=2.35.1
  - libgfortran-ng=9.3.0
  - libedit=3.1.20191231
  - libev=4.33
  - nspr=4.29
  - dbus=1.13.6
  - libxkbcommon=1.0.3
  - nettle=3.6
  - jasper=1.900.1
  - libgomp=9.3.0
  - libuuid=2.32.1
  - libstdcxx-ng=9.3.0
  - readline=8.0
  - gst-plugins-base=1.14.5
  - openh264=2.1.1
  - x264=1!152.20180806
  - gmp=6.2.1
  - ncurses=6.2
  - nss=3.60
  - libnghttp2=1.41.0
  - _openmp_mutex=4.5
  - lame=3.100
  - gnutls=3.6.13
```

**Comment by aashrafh** [comment]
Mostly, they are platform-specific packages. I already deleted them and tested the code on my Windows 10 machine but it seems that I posted the file content before saving it. Sorry for that.

```
name: mozart
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - anyio=2.0.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - cloudpickle=1.6.0
  - cryptography=3.3.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2020.12.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.4
  - graphite2=1.3.13
  - gstreamer=1.18.2
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=3.3.0
  - importlib_metadata=3.3.0
  - imutils=0.5.3
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyter_server=1.1.3
  - jupyterlab=3.0.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.0
  - libcurl=7.71.1
  - libevent=2.1.10
  - libffi=3.3
  - libglib=2.66.4
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.0.0
  - libopenblas=0.3.12
  - libopencv=4.5.0
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.3
  - mistune=0.8.4
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nbclassic=0.2.5
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.3
  - networkx=2.5
  - notebook=6.1.6
  - numpy=1.19.4
  - olefile=0.46
  - opencv=4.5.0
  - openssl=1.1.1i
  - packaging=20.8
  - pandoc=2.11.3.1
  - pandocfilters=1.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - pixman=0.40.0
  - prometheus_client=0.9.0
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py-opencv=4.5.0
  - pycparser=2.20
  - pygments=2.7.3
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.12.9
  - requests=2.25.1
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - sniffio=1.2.0
  - sqlite=3.34.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - autopep8==1.5.4
    - pycodestyle==2.6.0
    - toml==0.10.2
 ```

**Comment by ken830** [comment]
@aashrafh: That worked! I was able to setup the environment. Thank you!

**Comment by dzen-it** [comment]
@aashrafh Small request. Please push last worked requirements file to repository, it's realy works on macOS Catalina. Thanks!

**Comment by aashrafh** [comment]
@dzen-it  Done. Thank you for the macOS confirmation

**Comment by Hunue-Park** [comment]
Thank you for your project source! I did it on Mac OS 'BIg Sur'
