### ISSUE TITLE
Import Error, 'Symbol not Found'

### ISSUE THREAD

**Issue by Hunue-Park** [aashrafh/Mozart#9]
Hello @aashrafh ! thank you for your repo. 
I'm successfully done on install step3. "conda activate mozart"
but when I get through step4, It gives me an error 'Symbol not Found' 
and also I wonder that do I need to run main.py file on Mozart-main/src/ directory? I'm not sure about this step. 
my environment is macOS, BIg Sur.

this is the error I got. 
`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from pre_processing import *
  File "/Users/parkhyunwoo/opt/anaconda3/envs/mozart/Mozart-main/src/pre_processing.py", line 4, in <module>
    import cv2
ImportError: dlopen(/Users/parkhyunwoo/opt/anaconda3/envs/mozart/lib/python3.7/site-packages/cv2.cpython-37m-darwin.so, 2): Symbol not found: _mp_get_memory_functions
  Referenced from: /Users/parkhyunwoo/opt/anaconda3/envs/mozart/lib/libgnutls.30.dylib
  Expected in: /Users/parkhyunwoo/opt/anaconda3/envs/mozart/lib/libhogweed.4.dylib
 in /Users/parkhyunwoo/opt/anaconda3/envs/mozart/lib/libgnutls.30.dylib`

**Comment by aashrafh** [comment]
It seems that you have a problem with the OpenCV version. the version used in the code doesn't work for your machine so try to downgrade it.
 You can find more details [here](https://stackoverflow.com/questions/60254766/opencv-giving-an-error-whenever-import-cv2-is-used)
